---
# vars file for ./roles/get_VpnDokuDB_info

# Directories 'vars' and 'defaults' both house variables, but variables
# in 'vars' have a higher priority, which means that they are more
# difficult to override.
# Variables in 'defaults' have the lowest priority of any variables
# available, which means they’re easy to override.

# Information to access VPN-Doku-DB in DB Systel Lab Environment
#"vpn_doku_db": {
#  "description": "VPN-Doku-DB Lab Server",
#  "base_url": "https://ffmvsipam1.lanbf.db.de",
#  "verify_server": False,
#  "user": "nso_poc",
#  "pwd": "yiavizzTwZgh"
#}
# Information to access a mockup VPN-Doku-DB
"vpn_doku_db": {
  "description": "Postman Mock VPN-Doku-DB Server",
  "base_url": "https://6f1fcdb5-858d-4e47-8717-1184aaa5c191.mock.pstmn.io",
  "verify_server": True,
  "user": "unknown",
  "pwd": "unbekannt"
}
