---
##
## Example Playbook analyzing the output of a "show cdp neighbor" command
## executed on an IOS device.
##
## The playbook expects two extra variables to be defined on command line
## my_invname       inventory name of the device on which the "show cdp neighbor"
##                  command shall be executed
## my_nodeType      either "pe" or "ce"
## rmt_hostname     hostname of a remote device connected to the my_invname device
## rmt_nodetype     either "ce" or "cr" 
##
## Result:
## The play will set the following facts for the my_invname device
## if called with  my_nodeType=pe  and  rmt_nodetype=ce.
## pe_ce_ifType     Interface Type on PE Router towards CE.
## pe_ce_ifName     Interface name on PE Router towards CE.
## ce_pe_ifType     Interface Type on CE Router towards PE.
## ce_pe_ifName     Interface name on CE Router towards PE.
##
## If called with  my_nodeType=ce  and  rmt_nodetype=cr  the names are accordingly.
##  
## Usage:
##    ansible-playbook -i inventory -v get_interface_data.yml \
##            -e 'my_invname=R1_ios my_nodeType=pe rmt_hostname=R3_ios rmt_nodetype=ce'
##

- name: Example, analyze output of 'show cdp neighbor' executed on an IOS device
  gather_facts: no
  hosts: "{{my_invname}}"

  tasks:
    - name: Execute 'show cdp neighbor' command
      ios_command:
        commands:
          - show cdp neighbor
      register: cdpn_result
      when: "ansible_network_os == 'ios'"

    - name: Display 'show cdp neighbor' output
      debug:
        var: cdpn_result.stdout[0]
        verbosity: 1

    - name: Analyze 'show cdp neighbor' output
      set_fact:
        neighbor_data: "{{''.join( [rmt_hostname, cdpn_result.stdout[0].replace('\n', '@@@').replace('\r', '').replace('@@@ ', ' ').partition(rmt_hostname)[2].split('@@@', 1)[0]] ).split()}}"

    - name: Store interface data in facts cache
      set_fact:
        "{{my_nodeType}}_{{rmt_nodetype}}_ifType": "{{neighbor_data[1]}}"
        "{{my_nodeType}}_{{rmt_nodetype}}_ifName": "{{neighbor_data[2]}}"
        "{{rmt_nodetype}}_{{my_nodeType}}_ifType": "{{neighbor_data[6]}}"
        "{{rmt_nodetype}}_{{my_nodeType}}_ifName": "{{neighbor_data[7]}}"

    - name: Show stored interface data
      debug:
        msg: |
             Local interface on {{my_invname}}: pe_ce_ifType={{pe_ce_ifType}}, pe_ce_ifName={{pe_ce_ifName}}
             Remote interface on {{rmt_hostname}}: ce_pe_ifType={{ce_pe_ifType}}, ce_pe_ifName={{ce_pe_ifName}}
...
